# Generated by Django 5.2 on 2025-05-07 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='requester',
            field=models.ForeignKey(limit_choices_to={'user_type': 'solicitante'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
    ]
