# Generated by Django 5.2 on 2025-05-08 02:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='devotional_text',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='invitation_details',
        ),
        migrations.RemoveField(
            model_name='event',
            name='program',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speaker_bios',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='eventrequest',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_event', to='events.eventrequest', verbose_name='Solicitação de Evento Original (se houver)'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Imagem do Evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Evento pendente', max_length=200, verbose_name='Nome do Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Organizador/Departamento'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Curta'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('cancelled', 'Cancelado'), ('completed', 'Concluído')], default='draft', max_length=10, verbose_name='Status do Evento'),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 8, 2, 25, 41, 2376, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='event_name_proposal',
            field=models.CharField(default='Nome da Proposta Pendente', max_length=200, verbose_name='Nome Proposto do Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Data e Hora do Evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Local do Evento'),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='requester',
            field=models.ForeignKey(limit_choices_to={'user_type': 'solicitante'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_event_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
    ]
