# Generated by Django 5.2 on 2025-05-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_remove_event_devotional_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imagem_destaque',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_destaques/'),
        ),
    ]
