# Generated by Django 5.2 on 2025-05-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_imagem_destaque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Palestrante')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Minibiografia')),
                ('lattes_link', models.URLField(blank=True, null=True, verbose_name='Link do Currículo Lattes')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers_photos/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Palestrante',
                'verbose_name_plural': 'Palestrantes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.speaker', verbose_name='Palestrantes'),
        ),
    ]
