# Generated by Django 5.2 on 2025-05-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_speaker_event_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stream_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link da Transmissão (TV Mackenzie)'),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='stream_requested',
            field=models.BooleanField(default=False, verbose_name='Solicita Transmissão pela TV Mackenzie?'),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='suggested_stream_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Sugerido para Transmissão (se houver)'),
        ),
    ]
