# Generated by Django 5.2 on 2025-05-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_stream_link_eventrequest_stream_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='devotional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Devocional'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Término'),
        ),
        migrations.AddField(
            model_name='event',
            name='invitation_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes do Convite'),
        ),
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.TextField(blank=True, null=True, verbose_name='Programação do Evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker_bios',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia dos Palestrantes (texto)'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Início'),
        ),
    ]
